language: java
sudo: required
dist: trusty

install:
  - ./gradlew assemble

script:
  - ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: false
  include:
    - env: JDK='Open JDK 8'
      jdk: openjdk8
    - env: JDK='Open JDK 9'
      jdk: openjdk9
    - env: JDK='Open JDK 10'
      jdk: openjdk10
    - env: JDK='Open JDK 11'
      jdk: openjdk11
  allow_failures:
    - env: JDK='Open JDK 9'
    - env: JDK='Open JDK 11'

notifications:
  email: false